// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ClearData4hML.Model
{
    public class ModelInput
    {
        [ColumnName("Segment"), LoadColumn(0)]
        public string Segment { get; set; }


        [ColumnName("gamecategory"), LoadColumn(1)]
        public string Gamecategory { get; set; }


        [ColumnName("subgamecategory"), LoadColumn(2)]
        public string Subgamecategory { get; set; }


        [ColumnName("bundle"), LoadColumn(3)]
        public string Bundle { get; set; }


        [ColumnName("created"), LoadColumn(4)]
        public string Created { get; set; }


        [ColumnName("shift"), LoadColumn(5)]
        public string Shift { get; set; }


        [ColumnName("oblast"), LoadColumn(6)]
        public string Oblast { get; set; }


        [ColumnName("city"), LoadColumn(7)]
        public string City { get; set; }


        [ColumnName("os"), LoadColumn(8)]
        public string Os { get; set; }


        [ColumnName("osv"), LoadColumn(9)]
        public string Osv { get; set; }


    }
}
