// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using ClearData4hML.Model;
using CsvHelper;

namespace ClearData4hML.ConsoleApp
{
    public class input
    {
        public string gamecategory { get; set; }
        public string subgamecategory { get; set; }
        public string bundle { get; set; }
        public string created { get; set; }
        public string shift { get; set; }
        public string oblast { get; set; }
        public string city { get; set; }
        public string os { get; set; }
        public string osv { get; set; }
    }
    public class output
    {
        public string Segment { get; set; }
        public string gamecategory { get; set; }
        public string subgamecategory { get; set; }
        public string bundle { get; set; }
        public string created { get; set; }
        public string shift { get; set; }
        public string oblast { get; set; }
        public string city { get; set; }
        public string os { get; set; }
        public string osv { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            /*
             * Счётчик
            int all = 0;
            int well = 0;
            int bad = 0;
            */
            List<output> go = new List<output>();

            string inputpath = "C:\\Users\\skripnikov.sv0832\\Desktop\\test.csv"; //сюда ввести путь для 
            string outputpath = "C:\\Users\\skripnikov.sv0832\\Desktop\\result.csv"; // Сюда ввести путь для сохранения результата

            /*
             * Раскомментировать для задания иных путей
            Console.Write("Введите путь к файлу данных: ");
            inputpath = Console.ReadLine();

            Console.Write("Введите путь для сохранения результата: ");
            outputpath = Console.ReadLine();
            */

            using (var reader = new StreamReader(inputpath))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                var records = csv.GetRecords<input>();

                foreach (var record in records)
                {
                    ModelInput Data = new ModelInput()
                    {
                        Gamecategory = record.gamecategory,
                        Subgamecategory = record.subgamecategory,
                        Bundle = record.bundle,
                        Created = record.created,
                        Shift = record.shift,
                        Oblast = record.oblast,
                        City = record.city,
                        Os = record.os,
                        Osv = record.osv,
                    };

                    var Result = ConsumeModel.Predict(Data);

                    /*
                     * Счётчик
                    all++;
                    if (Result.Prediction == record.Segment)
                    {
                        well++;
                    }
                    else
                    {
                        bad++;
                    }
                    */
                }
            }

            /*
             * Счётчик
            Console.WriteLine("All: " + all);
            Console.WriteLine("Well: " + well);
            Console.WriteLine("Bad: " + bad);
            Console.WriteLine("Точность: " + (well * 100) / all);
            Console.ReadKey();
            */

            IEnumerable<output> recordss = go;

            using (var writer = new StreamWriter(outputpath))
            using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
            {
                csv.WriteRecords(recordss);
            }

            /*
             * 
             * Пример работы с моделью
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Gamecategory = @"Games",
                Subgamecategory = @"Racing",
                Bundle = @"com.MadOut.BIG",
                Created = @"2021-07-05 18:07:40",
                Shift = @"MSK+6",
                Oblast = @"Забайкальский Край",
                City = @"Чита",
                Os = @"android",
                Osv = @"10.0",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Segment with predicted Segment from sample data...\n\n");
            Console.WriteLine($"Gamecategory: {sampleData.Gamecategory}");
            Console.WriteLine($"Subgamecategory: {sampleData.Subgamecategory}");
            Console.WriteLine($"Bundle: {sampleData.Bundle}");
            Console.WriteLine($"Created: {sampleData.Created}");
            Console.WriteLine($"Shift: {sampleData.Shift}");
            Console.WriteLine($"Oblast: {sampleData.Oblast}");
            Console.WriteLine($"City: {sampleData.City}");
            Console.WriteLine($"Os: {sampleData.Os}");
            Console.WriteLine($"Osv: {sampleData.Osv}");
            Console.WriteLine($"\n\nPredicted Segment value {predictionResult.Prediction} \nPredicted Segment scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
            */
        }
    }
}
